<a href="https://colab.research.google.com/github/ishanegi7/CREDIT_CARD_FRAUD_DETECTION/blob/main/Copy_of_CREDIT_CARD_FRAUD_DETECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#IMPORTING THE DEPENDENCIES
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading tha data to pd dataframe
credit_card_data= pd.read_csv('/creditcard.csv')

In [ ]:
#5 lines of data
credit_card_data.head()
#data info
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152629 entries, 0 to 152628
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    152629 non-null  int64
 1   V1      152629 non-null  float64
 2   V2      152629 non-null  float64
 3   V3      152629 non-null  float64
 4   V4      152629 non-null  float64
 5   V5      152629 non-null  float64
 6   V6      152629 non-null  float64
 7   V7      152629 non-null  float64
 8   V8      152628 non-null  float64
 9   V9      152628 non-null  float64
 10  V10     152628 non-null  float64
 11  V11     152628 non-null  float64
 12  V12     152628 non-null  float64
 13  V13     152628 non-null  float64
 14  V14     152628 non-null  float64
 15  V15     152628 non-null  float64
 16  V16     152628 non-null  float64
 17  V17     152628 non-null  float64
 18  V18     152628 non-null  float64
 19  V19     152628 non-null  float64
 20  V20     152628 non-null  float64
 21  V21     152628 non-null  float64
 22  V22     152628 non-null  float64
 23  V23     152628 non-null  float64
 24  V24     152628 non-null  float64
 25  V25     152628 non-null  float64
 26  V26     152628 non-null  float64
 27  V27     152628 non-null  float64
 28  V28     152628 non-null  float64
 29  Amount  152628 non-null  float64
 30  Class   152628 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 36.1 MB

In [ ]:
#no of missing values in each column

credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#to see distribution of legit transaction and  fraudalent transaction
credit_card_data['Class'].value_counts()

Class
0.0    152298
1.0       330
Name: count, dtype: int64

THE DATA IS HIGHLY UNBALANCED


0--> NORMAL TRANSACTION

1--> FRAUDALENT TRANSACTION

In [ ]:
#separating the data for analaysis
LEGIT= credit_card_data[credit_card_data.Class ==0]
FRAUD= credit_card_data[credit_card_data.Class ==1]

In [ ]:
print(LEGIT.shape)
print(FRAUD.shape)

(152298, 31)
(330, 31)

In [ ]:
#statistical measure of the data
LEGIT.Amount.describe()

count    152298.000000
mean         88.762926
std         246.776996
min           0.000000
25%           5.840000
50%          22.710000
75%          79.000000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
FRAUD.Amount.describe()

count     330.000000
mean      115.783606
std       233.695450
min         0.000000
25%         1.000000
50%        12.310000
75%       103.397500
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,54905.417425,-0.226625,0.035112,0.628662,0.123235,-0.232836,0.073228,-0.089445,0.050731,-0.035221,...,0.039485,-0.039747,-0.110632,-0.028781,0.011968,0.117875,0.022418,0.001432,0.002775,88.762926
1.0,52195.178788,-5.938595,4.257998,-7.859258,4.800682,-4.405201,-1.530096,-6.721001,1.254498,-2.814301,...,0.308288,1.038752,-0.134902,-0.058691,-0.063835,0.121347,0.037563,0.267357,0.057408,115.783606

UNDER SAMPLING


Build a sample dataset containing similar distribtution of normal transaction and fraudalent transaction..

In [ ]:
LEGIT_sample= LEGIT.sample(n=492)

CONCATING TWO DF

In [ ]:
LEGIT_sample= LEGIT.sample(n=492)
new_dataset =pd.concat([LEGIT_sample , FRAUD ],axis=0)
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
124140,77189,1.304762,-1.311671,0.638147,-1.449016,-1.583221,-0.120215,-1.221234,0.127097,-1.919847,...,-0.261583,-0.562060,0.152416,-0.053709,-0.012634,-0.401545,0.041043,0.024897,70.65,0.0
121006,76041,-0.261102,0.601870,1.641727,0.676767,-0.297138,-0.423031,0.362879,0.020200,0.113567,...,0.017728,0.247761,-0.106521,0.437839,-0.417304,0.406696,0.138503,0.155188,11.50,0.0
84527,60344,-0.645922,0.632744,-0.009355,-1.086404,1.697358,3.689484,-0.529229,1.434339,-0.429823,...,0.090015,-0.086934,0.104655,1.007429,-0.528017,0.153429,0.008375,0.102499,43.51,0.0
13834,24532,1.136197,0.324848,0.510349,1.373091,-0.240138,-0.641812,0.048202,-0.170898,1.322094,...,-0.066264,0.057639,-0.031161,0.337733,0.521069,-0.358139,-0.004047,0.016691,27.49,0.0
9788,14495,-0.781384,0.976666,2.156384,3.373360,0.554487,0.816177,1.061022,-0.422139,0.391295,...,-0.302266,0.036729,-0.085695,-0.028013,0.256226,0.293456,-0.294916,-0.380055,104.97,0.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    330
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,52918.926829,-0.223244,0.150661,0.572293,0.114166,-0.152285,0.102579,-0.115239,0.072472,-0.041208,...,0.059172,-0.054448,-0.125625,-0.051403,-0.000552,0.094858,0.008395,0.010506,-0.002488,75.049106
1.0,52195.178788,-5.938595,4.257998,-7.859258,4.800682,-4.405201,-1.530096,-6.721001,1.254498,-2.814301,...,0.308288,1.038752,-0.134902,-0.058691,-0.063835,0.121347,0.037563,0.267357,0.057408,115.783606

Splitting the data into Features & Tarrgets

In [ ]:
X = new_dataset.drop('Class', axis=1)
Y= new_dataset['Class']

In [ ]:
print(X)

         Time         V1         V2         V3         V4         V5  \
124140  77189   1.304762  -1.311671   0.638147  -1.449016  -1.583221
121006  76041  -0.261102   0.601870   1.641727   0.676767  -0.297138
84527   60344  -0.645922   0.632744  -0.009355  -1.086404   1.697358
13834   24532   1.136197   0.324848   0.510349   1.373091  -0.240138
9788    14495  -0.781384   0.976666   2.156384   3.373360   0.554487
...       ...        ...        ...        ...        ...        ...
151730  96135  -1.952933   3.541385  -1.310561   5.955664  -1.003993
151807  96291  -3.552173   5.426461  -3.731810   6.679062  -2.187543
152019  96717  -3.705856   4.107873  -3.803656   1.710314  -3.582466
152223  97121 -17.976266  12.864989 -19.575066  11.345120 -13.998646
152295  97235 -17.537592  12.352519 -20.134613  11.122771 -14.571080

              V6         V7         V8        V9  ...       V20       V21  \
124140 -0.120215  -1.221234   0.127097 -1.919847  ... -0.265670 -0.261583
121006 -0.423031   0.362879   0.020200  0.113567  ... -0.016378  0.017728
84527   3.689484  -0.529229   1.434339 -0.429823  ...  0.052875  0.090015
13834  -0.641812   0.048202  -0.170898  1.322094  ... -0.217706 -0.066264
9788    0.816177   1.061022  -0.422139  0.391295  ...  0.242467 -0.302266
...          ...        ...        ...       ...  ...       ...       ...
151730  0.983049  -4.587235  -4.892184 -2.516752  ...  1.965030 -1.998091
151807  2.433940  -8.748110 -12.108284 -2.856359  ...  3.792667 -5.688990
152019  1.469729  -9.621560 -11.913105 -0.322297  ...  3.639603 -5.498772
152223 -0.354900 -23.783470  -4.872353 -8.504285  ...  2.419921 -4.300432
152295 -0.381622 -23.928661  -4.724921 -8.603038  ...  1.925103 -4.352213

             V22       V23       V24       V25       V26       V27       V28  \
124140 -0.562060  0.152416 -0.053709 -0.012634 -0.401545  0.041043  0.024897
121006  0.247761 -0.106521  0.437839 -0.417304  0.406696  0.138503  0.155188
84527  -0.086934  0.104655  1.007429 -0.528017  0.153429  0.008375  0.102499
13834   0.057639 -0.031161  0.337733  0.521069 -0.358139 -0.004047  0.016691
9788    0.036729 -0.085695 -0.028013  0.256226  0.293456 -0.294916 -0.380055
...          ...       ...       ...       ...       ...       ...       ...
151730  1.133706 -0.041461 -0.215379 -0.865599  0.212545  0.532897  0.357892
151807  2.510980  0.953933 -0.542506 -0.620152  0.406013  0.023025  0.164741
152019  2.941475  0.916236 -0.255504 -0.183835 -0.584539 -0.315484 -0.097223
152223  2.865772  1.489302  0.386039 -0.232392  0.413827 -3.255981 -0.538963
152295  2.389041  2.019128  0.627192 -1.085997 -0.071803 -3.838198 -0.802564

        Amount
124140   70.65
121006   11.50
84527    43.51
13834    27.49
9788    104.97
...        ...
151730   18.96
151807   33.59
152019    1.00
152223    8.64
152295    9.82

[822 rows x 30 columns]

In [ ]:
print(Y)

124140    0.0
121006    0.0
84527     0.0
13834     0.0
9788      0.0
         ...
151730    1.0
151807    1.0
152019    1.0
152223    1.0
152295    1.0
Name: Class, Length: 822, dtype: float64

Split the data into Training data & Testing data

In [ ]:
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.2 , stratify=Y , random_state=2)

In [ ]:
print(X.shape, X_train.shape , X_test.shape)

(822, 30) (657, 30) (165, 30)

MODEL TRAINING


Logistic Regression

In [ ]:
#training the Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train , Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

Model Evaluation

Accuracy Score

In [ ]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy= accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training Data :', training_data_accuracy)

Accuracy on Training Data : 0.9573820395738204

In [ ]:
#accuracy on training data
X_test_prediction = model.predict(X_test)
test_data_accuracy= accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy on Test Data :', test_data_accuracy)

Accuracy on Test Data : 0.9393939393939394